from .residencia import ResidenciaSchema
from .usuario import UsuarioSchema
from .area_residencia import Area_ResidenciaSchema
from .dispositivo import Dispositivo_Schema
from .log_exec import Log_Exec_Schema
#from .payments import PaymentSchema
#from .vendas import OrderSchema
#from .historico import HistoricoSchema
#from .regras import RegraSchema