"""Tipo e info nos dispositivos

Revision ID: 6413dc98e9d2
Revises: c14ab2492ae2
Create Date: 2023-10-25 03:25:33.253977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6413dc98e9d2'
down_revision = 'c14ab2492ae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('info', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.drop_column('info')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
