"""Mudança tipo info em dispositivos

Revision ID: 9df9bdcb6f13
Revises: 6413dc98e9d2
Create Date: 2023-10-26 03:16:23.405942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df9bdcb6f13'
down_revision = '6413dc98e9d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.alter_column('info',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.alter_column('info',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
