"""info de string para json

Revision ID: a670b4e68232
Revises: b4ac4cf85626
Create Date: 2024-04-14 20:53:35.707884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a670b4e68232'
down_revision = 'b4ac4cf85626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.alter_column('info',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.alter_column('info',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
