"""Mudanca em dispositivos

Revision ID: b4ac4cf85626
Revises: 9df9bdcb6f13
Create Date: 2024-01-24 00:16:57.886899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ac4cf85626'
down_revision = '9df9bdcb6f13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivo', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
