from .base import Base
from .residencia import Residencia
from .area_residencia import Area_Residencia
from .usuario import Usuario
from .dispositivo import Dispositivo
from .log_exec import Log_Exec
#from .payments import Payment
#from .vendas import Order
#from .historico import Historico
#from .regras import Regra